### ISSUE TITLE
Incompatible with token lean

### ISSUE THREAD

**Issue by seancroach** [caewok/fvtt-elevated-vision#101]
Only using wall height, elevated vision, libWrapper, and token lean, this module no longer works even in a completely new campaign.

**Comment by caewok** [comment]
Well, I cannot get Token Lean to work without any other modules enabled. It gives me:

```
script.mjs:164 Uncaught TypeError: Cannot read properties of undefined (reading 'getMovementAdjustedPoint')
    at enableLean (script.mjs:164:43)
    at Object.onUp (script.mjs:100:13)
    at KeyboardManager._executeKeybind (foundry.js:2501:58)
    at KeyboardManager._processKeyboardContext (foundry.js:2543:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2601:10)
    at foundry.js:2228:52
```
