### ISSUE TITLE
Compatibility with Levels?

### ISSUE THREAD

**Issue by naesean** [caewok/fvtt-elevated-vision#12]
I have been looking for a module to do exactly this for awhile. Thank you! Unfortunately... I use Levels extensively. Any chance you'll work on compatibility between the modules?

**Comment by caewok** [comment]
Yes, I would like to get to compatibility with Levels. Maybe once I improve compatibility with Perfect Vision...

**Comment by caewok** [comment]
Compatibility introduced in v0.1.2. I am sure issues remain, so feel free to file new bug reports when you find them!

**Comment by naesean** [comment]
Thank you! I'll check it out.

**Comment by naesean** [comment]
Still experiencing an issue. It works okay as the GM but the when a player joins, they get this error in the console and the scene won't render --

`Uncaught TypeError: Cannot read properties of undefined (reading 'point')
[Detected 4 packages: elevatedvision, lib-wrapper, perfect-vision, levels]
    at create3dTestPoints (tokens.js:140:35)
    at DetectionModeBasicSight.testVisibilityDetectionMode (tokens.js:181:51)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at 🎁CanvasVisibility.prototype.testVisibility#perfect-vision (visibility.js:219:49)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at CanvasVisibility.visibilityWrapper (wrappers.js:94:25)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:189:20)
    at get isVisible [as isVisible] (foundry.js:45246:38)
    at CanvasVisibility.restrictVisibility (foundry.js:33168:68)
    at 🎁CanvasVisibility.prototype.refresh#perfect-vision (visibility.js:144:18)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CanvasVisibility.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at #update (foundry.js:41208:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)`
