### ISSUE TITLE
Error and canvas freeze with Alternative Token Visibility and Wall Height

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#29]
In a scene I have made to test issues while I have the following modules enabled (most of which are just library modules that don't do anything that I keep enabled for testing), the canvas freezes and an error is thrown whenever one token in particular is clicked on (Bharram Flatgranite):
![image](https://user-images.githubusercontent.com/12570777/200023746-e2469768-38dc-4cfd-b1c0-5f256ad835e1.png)
![image](https://user-images.githubusercontent.com/12570777/200023768-ad3370a5-aa13-47e4-923f-acf548b93253.png)

The error that is thrown is:

```
libWrapper-wrapper.js:669 Uncaught TypeError: Cannot read properties of undefined (reading 'rangeBottom')
[Detected 3 packages: elevatedvision, lib-wrapper, tokenvisibility]
    at isWallUnderneathTile (clockwise_sweep.js:84:46)
    at clockwise_sweep.js:41:30
    at Set.filter (commons.js:3000:12)
    at ClockwiseSweepPolygon._computeClockwiseSweepPolygon (clockwise_sweep.js:41:17)
    at 🎁ClockwiseSweepPolygon.prototype._compute#0 (libWrapper-wrapper.js:187:52)
    at ClockwiseSweepPolygon.compute (foundry.js:29659:10)
    at ClockwiseSweepPolygon.create (foundry.js:29629:17)
    at VisionSource._createPolygon (foundry.js:48162:37)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at VisionSource._createPolygonPointSource (visibility_los.js:92:10)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁PointSource.prototype._createPolygon#0 (libWrapper-wrapper.js:189:20)
    at VisionSource.initialize (foundry.js:49332:21)
    at Token5e.updateVisionSource (foundry.js:45606:19)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Token5e.tokenUpdateVisionSource (visibility_los.js:107:10)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype.updateVisionSource#0 (libWrapper-wrapper.js:189:20)
    at CanvasVisibility.initializeSources (foundry.js:32992:13)
    at #update (foundry.js:41329:61)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)
```

Here is an export of the scene:

[fvtt-Scene-space.txt](https://github.com/caewok/fvtt-elevated-vision/files/9940207/fvtt-Scene-space.txt)

**Comment by Zamrod** [comment]
The more I look, the more this is likely a bug in Alternate Token Visibility.

Right before the error there's a bunch of warnings from it:
```
visibility_range.js:103 Test point has los mapping already.
```

**Comment by caewok** [comment]
I just pushed an update. Try updating to v0.2.1 for Elevated Vision and let me know if that fixes the canvas error. 

Thanks for the scene export. I need to think more about the los mapping issue for Alt Token Visibility, which is mostly about caching already-tested points.

**Comment by caewok** [comment]
Closing as I think this is fixed now.
