### ISSUE TITLE
Cant move tokens

### ISSUE THREAD

**Issue by redjama** [caewok/fvtt-elevated-vision#61]
Noticed today I couldn't move a single token unless I used the arrow keys instead of dragging with the mouse.  Went through all my modules and found this one to be the culprit.  Turned off this module and the problem was fixed

**Comment by caewok** [comment]
I don't see that issue using Foundry v11.304 with dnd5e 2.2.2 and Elevated Vision v0.5.4. What version of Foundry, what system, and what version of Elevated Vision are you using? Also, do you see any error messages in the console when you attempt to drag a token using the mouse? (For most computers and browsers, F12 will bring up the console.)

**Comment by redjama** [comment]
> I don't see that issue using Foundry v11.304 with dnd5e 2.2.2 and Elevated Vision v0.5.4. What version of Foundry, what system, and what version of Elevated Vision are you using? Also, do you see any error messages in the console when you attempt to drag a token using the mouse? (For most computers and browsers, F12 will bring up the console.)

Im on V11.305 with dnd5e 2,2,2 and the most recent version of Elevated Vision.  I went through all my modules and I had the issue every single time this module was enabled.  Not sure if its conflicting with another module though. I didnt even look for error codes

**Comment by redjama** [comment]
> I don't see that issue using Foundry v11.304 with dnd5e 2.2.2 and Elevated Vision v0.5.4. What version of Foundry, what system, and what version of Elevated Vision are you using? Also, do you see any error messages in the console when you attempt to drag a token using the mouse? (For most computers and browsers, F12 will bring up the console.)

Uncaught TypeError: texture is undefined
[Detected 3 packages: elevatedvision, lib-wrapper, drag-ruler]
    fromTexture PixelCache.js:934
    #refreshElevationPixelCache ElevationLayer.js:777
    get elevationPixelCache ElevationLayer.js:769
    elevationAt ElevationLayer.js:798
    terrainElevationAt CoordinateElevationCalculator.js:152
    terrainElevation CoordinateElevationCalculator.js:160
    currentTokenState TravelElevationCalculator.js:996
    cloneToken tokens.js:283
    clone#0 libWrapper-wrapper.js:187
    _onDragLeftStart foundry.js:28909
    _onDragLeftStart foundry.js:56050
    call_wrapped libWrapper-wrapper.js:507
    onEntityLeftDragStart main.js:135
    call_wrapper libWrapper-wrapper.js:616
    _onDragLeftStart#0 libWrapper-wrapper.js:189
    callback foundry.js:31547
    #handleDragStart foundry.js:31874
    #handleMouseMove foundry.js:31856
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128
this is the error I got.  Maybe drag ruler is conflicting with it as well.  Not sure.  But drag ruler works when elevated vision isnt enabled

**Comment by sroakjp** [comment]
I'm having the same issue.
Foundry V11.306
Elevated Vision 0.5.4

Here is the error I'm seeing:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/62338951/3be445be-c0b5-426f-9bbd-7a5c5582d7c0)

**Comment by sroakjp** [comment]
My problems have gotten worse in v0.5.5. The one map I had that was working no longer works. In addition on one of the maps that was having the issue, overhead tiles won't disappear when I select a tile beneath them, as they are supposed to do.

Here's an example of the errors I'm seeing.
![image](https://github.com/caewok/fvtt-elevated-vision/assets/62338951/fd06fcf3-0eb7-4a1e-8d3f-25ba0eb416bc)

**Comment by Iakudo** [comment]
I have the same problem as sroakjp, with the same error message when clicking on a token, then again when pressing an arrow key, though it doesn't get thrown up again until I refresh the window and repeat the actions.

Additionally:

1.) When bringing up the console and causing the error message to be thrown, closing the console warps the aspect ratio of the canvas and I am unable to pan the view or zoom in/out.

2.) I have one world in which this issue does not come up at all, even with Levels and Elevated Vision installed. Not sure why there's a difference between the two worlds since they were created at the same time, use all the same settings, and modules.
![Levels conflict](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/9173bacd-eb76-47be-a5fb-bee13594427e)

**Comment by uniwars** [comment]
Hello, same problem :

Foundry v11 305
Pathfinder 2 5.2.2 (rule-based vision enabled)
Elevated vision 0.5.5
Levels 4.1.6
GM vision 1.0.3

libWrapper-wrapper.js:513 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'wall')
[Detected 5 packages: elevatedvision, lib-wrapper, levels, system:pf2e, gm-vision]
    at RenderedPointSource.js:505:44
    at Array.some (<anonymous>)
    at VisionSource.hasWallCollision (RenderedPointSource.js:504:25)
    at VisionSource.pointInShadow (RenderedPointSource.js:348:29)
    at VisionSource.targetInShadow (VisionSource.js:79:15)
    at DetectionModeBasicSight._testLOS (detection_modes.js:28:27)
    at 🎁DetectionMode.prototype._testLOS#0 (libWrapper-wrapper.js:187:52)
    at DetectionModeBasicSight._testPoint (detection_modes.js:41:14)
    at 🎁DetectionModeBasicSight.prototype._testPoint#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:49434:36
    at Array.some (<anonymous>)
    at DetectionModeBasicSight.testVisibility (foundry.js:49434:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionMode.prototype.testVisibility#levels (wrappers.js:186:20)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at DetectionModeBasicSight.testVisibility (pf2e.mjs:74:36132)
    at CanvasVisibility.testVisibility (foundry.js:38325:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.visibilityWrapper (wrappers.js:148:25)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:189:20)
    at get isVisible (pf2e.mjs:16:41008)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Token.tokenUIWrapperIsVisible (uiHandler.js:22:72)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Token.objectClass.prototype.isVisible#getter (libWrapper-wrapper.js:364:19)
    at Token._refreshVisibility (foundry.js:54815:25)
    at CanvasVisibility.restrictVisibility (foundry.js:38249:9)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CanvasVisibility.prototype.restrictVisibility#gm-vision (script.js:77:24)
    at 🎁CanvasVisibility.prototype.restrictVisibility#0 (libWrapper-wrapper.js:187:52)
    at CanvasVisibility.refresh (foundry.js:38084:10)
    at PerceptionManager.applyRenderFlags (foundry.js:50180:58)
    at #applyRenderFlags (foundry.js:27606:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)

It also makes player unable to see the scene even with an owned token on it.

**Comment by dg1m** [comment]
I'm running 11.306 with PF2E 5.2.3 in an unRaid docker. I have the same issue. It's only an issue for me with Elevated Vision and Levels are both enabled. If either is disabled then everything works as expected.

Where is everyone getting these error outputs?

**Comment by Iakudo** [comment]
> 

Press F12 to bring up the console (this is the default key) and check the "errors" section. Might have a 0 next to the word if you don't have any errors. Whenever you encounter any bugs, they'll likely throw up a message with a red background in the console area.

**Comment by caewok** [comment]
Short term, if you disable "Override Visibility Tests" in the Elevated Vision settings, this will correct the issue with Levels

**Comment by caewok** [comment]
This error with Levels should be fixed in v0.5.6.  Thanks all for the reports! (Basically, Levels is overriding `hasWallCollision` in a problematic way, in that it is not returning the walls in the return data. That was unanticipated. I replaced the method with a custom one that avoids the issue. There may, however, be other compatibility issues with Levels related to this.)
